# Generated by Django 4.1.3 on 2022-11-05 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PettyQuestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreOrg', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('geolocalizaicion', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AsociacionVeterinaria',
                'verbose_name_plural': 'AsociacionesVeterinarias',
                'db_table': 'AsociacionVeterinaria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='contratoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comporbanteDomicilio', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('ine', models.CharField(max_length=200)),
                ('razones', models.CharField(max_length=1000)),
                ('idAsociacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.asociacionveterinaria')),
            ],
            options={
                'verbose_name': 'contratoAdopcion',
                'verbose_name_plural': 'contratosAdopcion',
                'db_table': 'contratoAdopcion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'Especie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
                'db_table': 'Estatus',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('claveRemitente', models.CharField(max_length=200)),
                ('claveDestinatario', models.CharField(max_length=200)),
                ('usuario', models.SmallIntegerField()),
                ('cartilla', models.CharField(max_length=200)),
                ('mascota', models.CharField(max_length=200)),
                ('visto', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensaje',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['id'], 'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tipo',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='Mascota',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('geolocalizaicion', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAnt', models.DateField()),
                ('fechaActual', models.DateField(default=django.utils.timezone.now)),
                ('fechaSig', models.DateField()),
                ('claveContrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.contratoadopcion')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'Notificacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='fk_mascota_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveMascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.mascota')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.usuario')),
            ],
            options={
                'verbose_name': 'fk_mascota_usuario',
                'verbose_name_plural': 'fk_mascota_usuario',
                'db_table': 'fk_mascota_usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='fk_mascota_asociacionveterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveAsociacionVeterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.asociacionveterinaria')),
                ('claveMascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.mascota')),
            ],
            options={
                'verbose_name': 'fk_mascota_asociacionveterinaria',
                'verbose_name_plural': 'fk_mascota_asociacionveterinaria',
                'db_table': 'fk_mascota_asociacionveterinaria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='fk_contrato_mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveContrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.contratoadopcion')),
                ('claveMascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.mascota')),
            ],
            options={
                'verbose_name': 'fk_contrato_mascota',
                'verbose_name_plural': 'fk_contrato_mascota',
                'db_table': 'fk_contrato_mascota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='fk_contrato_asociacionveterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveAsociacionVeterinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.asociacionveterinaria')),
                ('claveContrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.contratoadopcion')),
            ],
            options={
                'verbose_name': 'fk_contrato_asociacionveterinaria',
                'verbose_name_plural': 'fk_contrato_asociacionveterinaria',
                'db_table': 'fk_contrato_asociacionveterinaria',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contratoadopcion',
            name='idMascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.mascota'),
        ),
        migrations.AddField(
            model_name='contratoadopcion',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='Especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.especie'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PettyQuestApp.estatus'),
        ),
    ]
